version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
stages:
  - name: image_build
    displayName: 镜像构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: account
        repository: crpi-cov44u3tj8fodq9j.cn-hangzhou.personal.cr.aliyuncs.com
        username: aliyun8628006919
        password: 143612Ab!
        tag: ${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./Dockerfile
        context: .
        artifacts: []
        isCache: false
        processorType:
          - amd64
        parameter: {}
        notify: []
        strategy:
          retry: '0'
